apiVersion: apps/v1
kind: Deployment
metadata:
  name: guerral-mu-aks-api
  namespace: guerral
  labels:
    app: guerral-mu-aks-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guerral-mu-aks-api
  template:
    metadata:
      labels:
        app: guerral-mu-aks-api
    spec:
      nodeSelector:
        'kubernetes.io/os': linux
      containers:
        - name: guerral-mu-aks-api
          image: acrmuaksguerraldev.azurecr.io/guerral-mu-aks-api:1.0
          resources:
            limits:
              memory: '256Mi'
              cpu: '100m'
          ports:
            - containerPort: 3001
