# Artifactory
releaseRepo: mfc-mu-npm

# Node
projectType: nodejs
nodeBuildCommand: npm ci
nodePackageCommand: npm pack

# Version
increasePatchVersion: true

# Sonar - Disable for lab exercises only
sonarQubeFailPipelineOnFailedQualityGate: false

# SNYK - Disable for lab exercises only
snykGatingEnabled: false

gitSSHCredentialsId: mu-emu-devops-ssh

# Docker
dockerImageName: guerral-mu-aks-api
dockerArtifactoryRepo: mfc-mu-docker

# Helm
chartLocation: ./helm
publishChart: true

# Name of the values file(s) seperated with spaces, where you want latest Docker tags dynamically updated for your images
dockerValuesFileName: values.yaml
